// Each route has its own file in the REST folder.

// REST
//-- admin.rest
//-- event.rest
//-- member.rest
//-- user.rest
//-- volunteer.rest

// With the .REST file in the active window, use the VS Code status bar to select your REST Client Environment.
// The Environment will select the {{host}} variable as defined in the workspace settings file.

// .vscode
//-- settings.json

