// NOTE: Before using this file, select your preferred REST Client environment on the status bar in VS Code.

### All objects
# @name allAdmins
GET {{host}}/administration

@adminId = {{allAdmins.response.body.$[0]._id}}

### Get a single object
# @name oneAdmin
GET {{host}}/administration/{{adminId}}

@firstName = {{oneAdmin.response.body.firstName}}
@lastName = {{oneAdmin.response.body.lastName}}
@address = {{oneAdmin.response.body.address}}
@phoneNumber = {{oneAdmin.response.body.phoneNumber}}
@email = {{oneAdmin.response.body.email}}
@position = {{oneAdmin.response.body.position}}

### Update record
PUT {{host}}/administration/{{adminId}}
Content-Type: application/json

{
    "firstName": "~~Testing~~",
    "lastName": "~~Testing~~",
    "address": "~~Testing~~",
    "phoneNumber": "(000) 000-0000",
    "email": "the.boss@example.com",
    "position": "~~Testing~~"
}

### Verify that record has changed
GET {{host}}/administration/{{adminId}}

### Reset record to original values
PUT {{host}}/administration/{{adminId}}
Content-Type: application/json

{
    "firstName": "{{firstName}}",
    "lastName": "{{lastName}}",
    "address": "{{address}}",
    "phoneNumber": "{{phoneNumber}}",
    "email": "{{email}}",
    "position": "{{position}}"
}

### Add a new record
# @name new
POST {{host}}/administration/
Content-Type: application/json

{
    "firstName": "~~Testing~~",
    "lastName": "~~Testing~~",
    "address": "~~Testing~~",
    "phoneNumber": "(000) 000-0000",
    "email": "the.boss@example.com",
    "position": "~~Testing~~"
}

#### Variables
@newId = {{new.response.body.insertedId}}

### Verify
GET {{host}}/administration/{{newId}}

### Delete
DELETE {{host}}/administration/{{newId}}

### Bad request to test validation
#! SHOULD FAIL with validation errors
PUT {{host}}/administration/not-an-id
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "phoneNumber": "(12) 34-5678",
    "email": "notAnEmail@badDomain"
}

#** Advanced queries **#

### 
GET {{host}}/administration?fields=email
Content-Type: application/json

{
    "firstName": "{{firstName}}",
    "lastName": "{{lastName}}"
}

### 
GET {{host}}/administration
Content-Type: application/json

{
    "position": { "$regex": "President" }
}