// NOTE: Before using this file, select your preferred REST Client environment on the status bar in VS Code.

###
# @name allMembers
GET {{host}}/members

@memberId = {{allMembers.response.body.$[0]._id}}

###
# @name oneMember
GET {{host}}/members/{{memberId}}

@firstName = {{oneMember.response.body.firstName}}
@lastName = {{oneMember.response.body.lastName}}
@address = {{oneMember.response.body.address}}
@phoneNumber = {{oneMember.response.body.phoneNumber}}
@email = {{oneMember.response.body.email}}
@birthday = {{oneMember.response.body.birthday}}
@allFamilyMembers = {{oneMember.response.body.allFamilyMembers}}

### Update existing record.
#! 401 Unauthorized
#* NOTE: You can use existing email address because it's the same record.
PUT {{host}}/members/{{memberId}}
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "address": "{{address}}",
  "phoneNumber": "{{phoneNumber}}",
  "email": "{{email}}",
  "birthday": "{{birthday}}",
  "allFamilyMembers": "{{allFamilyMembers}}"
}

### Create a new member with same field, SHOULD FAIL with email in use.
#! 401 Unauthorized
POST {{host}}/members
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "address": "{{address}}",
  "phoneNumber": "{{phoneNumber}}",
  "email": "{{email}}",
  "birthday": "{{birthday}}",
  "allFamilyMembers": "{{allFamilyMembers}}"
}

### Create a new member with new email.
#! 401 Unauthorized
# @name newMember
POST {{host}}/members
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "address": "{{address}}",
  "phoneNumber": "{{phoneNumber}}",
  "email": "{{$guid}}-{{email}}",
  "birthday": "{{birthday}}",
  "allFamilyMembers": "{{allFamilyMembers}}"
}

####
@newMemberId = {{newMember.response.body.insertedId}}

### Verify
GET {{host}}/members/{{newMemberId}}

### Clean up
#! 401 Unauthorized
DELETE {{host}}/members/{{newMemberId}}

### TESTING VALIDATION
#! 401 Unauthorized
PUT {{host}}/members/bad-id
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "address": "",
  "phoneNumber": "+1 (123) 456-7890",
  "email": "{{email}}",
  "birthday": "13-35-9999",
  "allFamilyMembers": ""
}