#* NOTE: Before using this file, select your preferred REST Client environment on the status bar in VS Code.

@userId = 6466d734172e9435fb18f97d
@weakPassword = awesomeSauce
@strongerPassword = awesomeSauce123!

### Attempt to steal users DB - SHOULD FAIL with 404 error.
GET {{host}}/users

### This should return "false" since the username is available.
GET {{host}}/users/exists/newSignup

### Get a single object
#! 401 Unauthorized
# @name oneUser
GET {{host}}/users/{{userId}}

@username = {{oneUser.response.body.username}}

### Log in
GET {{host}}/auth/login
Content-Type: application/json

{
    "username": "ptaPres",
    "password": "{{strongerPassword}}"
}

### This should return "true"
GET {{host}}/users/exists/{{username}}

### Add user -- SHOULD FAIL with password complexity error and duplicate user.
POST {{host}}/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{weakPassword}}"
}

### Add user -- SHOULD FAIL with duplicate user.
POST {{host}}/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{strongerPassword}}"
}

### Update user by id
#* This is allowed because we are updating an existing user.
PUT {{host}}/users/{{userId}}
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{strongerPassword}}"
}

### Add a new record
# @name newUser
POST {{host}}/users/
Content-Type: application/json

{
    "username": "{{username}}-123",
    "password": "{{strongerPassword}}"
}

#### Variables
@newUserId = {{newUser.response.body._id}}

### Verify
# TODO: Returns 400 if user not found, but probably should be 404.
GET {{host}}/users/{{newUserId}}

### Delete
DELETE {{host}}/users/{{newUserId}}

### BAD request to test validation
PUT {{host}}/users/bad-id
Content-Type: application/json

{
    "username": "",
    "password": "a"
}