// NOTE: Before using this file, select your preferred REST Client environment on the status bar in VS Code.

###
# @name allVolunteers
GET {{host}}/volunteers

@volunteerId = {{allVolunteers.response.body.$[0]._id}}

### Get a single object
# @name oneVolunteer
GET {{host}}/volunteers/{{volunteerId}}

@event = {{oneVolunteer.response.body.event}}
@opportunity = {{oneVolunteer.response.body.opportunity}}
@name = {{oneVolunteer.response.body.name}}

###
PUT {{host}}/volunteers/{{volunteerId}}
Content-Type: application/json

{
  "event": "{{event}}",
  "opportunity": "{{opportunity}}",
  "name": "{{name}}"
}

